import { prisma } from '@/lib/prisma'

export interface CreateNotificationData {
  userId: string
  title: string
  message: string
  type: 'info' | 'success' | 'warning' | 'error'
}

export async function createNotification(data: CreateNotificationData) {
  try {
    return await prisma.notification.create({
      data: {
        userId: data.userId,
        title: data.title,
        message: data.message,
        type: data.type
      }
    })
  } catch (error) {
    console.error('Error creating notification:', error)
    throw error
  }
}

export async function createBulkNotifications(notifications: CreateNotificationData[]) {
  try {
    return await prisma.notification.createMany({
      data: notifications
    })
  } catch (error) {
    console.error('Error creating bulk notifications:', error)
    throw error
  }
}

// Notification templates for common events
export const NotificationTemplates = {
  taskAssigned: (taskTitle: string, assigneeName: string) => ({
    title: 'New Task Assigned',
    message: `You have been assigned a new task: "${taskTitle}"`,
    type: 'info' as const
  }),

  taskCompleted: (taskTitle: string, assigneeName: string) => ({
    title: 'Task Completed',
    message: `Task "${taskTitle}" has been completed by ${assigneeName}`,
    type: 'success' as const
  }),

  taskStatusChanged: (taskTitle: string, newStatus: string, assigneeName: string) => ({
    title: 'Task Status Updated',
    message: `Task "${taskTitle}" status changed to ${newStatus} by ${assigneeName}`,
    type: 'info' as const
  }),

  attendanceCheckedIn: (employeeName: string, time: string) => ({
    title: 'Check-in Recorded',
    message: `${employeeName} checked in at ${time}`,
    type: 'success' as const
  }),

  attendanceCheckedOut: (employeeName: string, time: string) => ({
    title: 'Check-out Recorded',
    message: `${employeeName} checked out at ${time}`,
    type: 'success' as const
  }),

  attendanceLate: (employeeName: string, time: string, lateMinutes?: number) => ({
    title: 'Late Arrival',
    message: `${employeeName} arrived late at ${time}${lateMinutes ? ` (${lateMinutes} minutes late)` : ''}`,
    type: 'warning' as const
  }),

  attendanceEarly: (employeeName: string, time: string, earlyMinutes?: number) => ({
    title: 'Early Departure',
    message: `${employeeName} checked out early at ${time}${earlyMinutes ? ` (${earlyMinutes} minutes early)` : ''}`,
    type: 'warning' as const
  }),

  newEmployeeAdded: (employeeName: string, department: string) => ({
    title: 'New Employee Added',
    message: `${employeeName} has been added to ${department} department`,
    type: 'info' as const
  }),

  employeeUpdated: (employeeName: string, changes: string[]) => ({
    title: 'Employee Updated',
    message: `${employeeName}'s ${changes.join(', ')} has been updated`,
    type: 'info' as const
  }),

  taskDueSoon: (taskTitle: string, dueDate: string) => ({
    title: 'Task Due Soon',
    message: `Task "${taskTitle}" is due on ${dueDate}`,
    type: 'warning' as const
  }),

  taskOverdue: (taskTitle: string, dueDate: string) => ({
    title: 'Task Overdue',
    message: `Task "${taskTitle}" is overdue since ${dueDate}`,
    type: 'error' as const
  }),

  reportGenerated: (reportType: string, generatedBy: string) => ({
    title: 'Report Generated',
    message: `${reportType} report has been generated by ${generatedBy}`,
    type: 'info' as const
  })
}

// Helper function to get all managers and admins for notifications
export async function getManagersAndAdmins() {
  try {
    return await prisma.user.findMany({
      where: {
        role: {
          in: ['ADMIN', 'MANAGER']
        }
      },
      select: {
        id: true,
        name: true,
        role: true
      }
    })
  } catch (error) {
    console.error('Error fetching managers and admins:', error)
    return []
  }
}

// Helper function to get all employees in a department
export async function getEmployeesInDepartment(department: string) {
  try {
    return await prisma.employee.findMany({
      where: {
        department: department,
        isActive: true
      },
      include: {
        user: {
          select: {
            id: true,
            name: true
          }
        }
      }
    })
  } catch (error) {
    console.error('Error fetching employees in department:', error)
    return []
  }
}
